### ISSUE TITLE
Undefined method 'polymorphic_belongs_to?'

### ISSUE THREAD

**Issue by laCour** [ElMassimo/mongoid_includes#1]
Thanks for the gem! It's a big help. I've been running into an issue while trying to use it:

After using the gem in a manner exactly like your Albums example in the readme (i.e. same relations), I receive this error: `undefined method 'polymorphic_belongs_to?' for #<Array:0x00000005ce5798>`

This is the only relevant part of the backtrace which pertains to either the gem or mongoid:

```
mongoid_includes (1.0.1) lib/mongoid/includes/criteria.rb:41:in `includes'
```

This is being used within an engine. I'm using Mongoid version 4.0.2.

**Comment by ElMassimo** [comment]
Hello! The error suggests that [`from_metadata`](https://github.com/ElMassimo/mongoid_includes/blob/master/lib/mongoid/includes/criteria.rb#L41) is an `Array`.

That value is usually obtained as a result of calling [`inclusions.push`](https://github.com/ElMassimo/mongoid_includes/blob/aec508014905eed7b2336cb8e1c41654475f9c4a/lib/mongoid/includes/inclusions.rb#L20), which should always return a `Mongoid::Includes::Inclusion` instead.

The cause could be that [`inclusions`](https://github.com/ElMassimo/mongoid_includes/blob/aec508014905eed7b2336cb8e1c41654475f9c4a/lib/mongoid/includes/criteria.rb#L12) is not being overriden properly. I have [tested](https://github.com/ElMassimo/mongoid_includes/blob/aec508014905eed7b2336cb8e1c41654475f9c4a/spec/mongoid/includes/nested_inclusions_spec.rb#L47) the library with Mongoid [4.0.2](https://github.com/ElMassimo/mongoid_includes/blob/aec508014905eed7b2336cb8e1c41654475f9c4a/Gemfile.lock#L33), and using it in production with Mongoid 4.0.1, and it seems to work well.

A quick check that you can make to see if that's the case would be to run:
```ruby
Album.all.inclusions.class
=> Mongoid::Includes::Inclusions
```

I'd be happy to help you, but I will need a bit more information about the setup, like a sample gist that replicates the issue :smiley:

**Comment by laCour** [comment]
After some investigating I finally nailed down the cause. As it turns out, this is due to my multi-tenant application scoping queries for the engine to a relative tenant (i.e. `Client`). All models in the engine belong to one `Client`, and by default are scoped to their `Client`.

As such, `inclusions` on unscoped queries _are_ overridden, whereas for scoped queries it remains an `Array`. On the parent application, `Client.all.inclusions` is being overridden properly. Any ideas?

**Comment by ElMassimo** [comment]
Can you post a gist with a simplified version of the kind of scoping that you are using?

With the information that you have provided, I suspect that the problem could happen when you use [`merge`](https://github.com/mongodb/mongoid/blob/4.0.0-stable/lib/mongoid/criteria.rb#L296), the way that Mongoid performs the operation could potentially cause the `Mongoid::Includes::Inclusion` to degrade to a normal `Array`. I will release a new version with the fix in a few minutes.

**Comment by laCour** [comment]
Sure, here's exactly what's being included on the models (minus unrelated code): http://git.io/vCkMO

That sounds like it would be the cause. Thanks for your help!

**Comment by ElMassimo** [comment]
@laCour I have release version `1.0.2`, which should wrap the `Inclusions` properly for the Array operations that Mongoid performs on it. Let me know if it solves the issue for you :smiley:

**Comment by laCour** [comment]
You're the best. That seems to have fixed the issue. Thanks again!

**Comment by ElMassimo** [comment]
Thanks again for the bug report! Glad that you find the library useful!
