### ISSUE TITLE
Mongoid 7 support

### ISSUE THREAD

**Issue by FunkyloverOne** [ElMassimo/mongoid_includes#14]
Hey @ElMassimo, thanks for this nice gem, works better than native includes for me :)
But since Mongoid 7 is out, it would be great to be able to use this gem there as well.

**Comment by ElMassimo** [comment]
Sounds good, happy to accept any PRs to bump the Mongoid version, and release a new version right away.

Still haven't upgraded to Mongoid 7 in any of the apps that use this gem, so not sure if there are any incompatibilities that need to be fixed.

**Comment by ElMassimo** [comment]
Gotcha, that will probably require a major rewrite of this gem. Don't have a time estimate for when, since we are not planning to update the project to Mongoid 7 yet, but it will happen eventually.

**Comment by ilyazub** [comment]
https://github.com/unused/mongoid_includes/tree/mongoid7-wip seems to support Mongoid 7.

**Comment by ElMassimo** [comment]
Added support for Mongoid 7. Notifying anyone that has forked it, just in case it's useful.

@cotocisternas @unused @sagarkt @xenodata-lab @xenodera @madAle @stefangomez

I apologize for the noise if you are no longer using this library 🙇
