### ISSUE TITLE
🚨 Even the most basic "model.includes" is not working! 🚨

### ISSUE THREAD

**Issue by Victorcorcos** [ElMassimo/mongoid_includes#17]
# Issue 🚨

Hello @ElMassimo 

I was trying to test your Gem, but looks like the preload is not working. ⚠️ 

The issue is that: **The Bullet gem is still accusing N+1 Query Problem even after applying the `.includes` inside the query.**
Looks like the N+1 Query Problem is still happening after using `.includes`.

The example is pretty straightforward:

* **records** _→(has_many)_ **attachments** _→(belongs_to)_ **project**

# Scenario 🌍 

```rb
class Record < ApplicationRecord
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :attachments
end

class Attachment < ApplicationRecord
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :project
  belongs_to :record, optional: true
end

class Project < ApplicationRecord
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :records
  has_many :attachments

  field :id, type: String
end
```

# Steps to Reproduce 🚶 ...

To this topic, I'll present several queries and their output on the `bullet.log`, comparing the output before `mongoid_includes` and after `mongoid_includes`.

Just enter on `rails console` and execute the following commands.

#### 1. With N+1 Query Problem
```rb
Bullet.profile do
  query = Record.where(project_id: '621ea9b069ca9c07aec7e36d')
  query.map do |r| 
    r.attachments.map do |a|
      a.project.id
    end
  end
end
```

* Before `mongoid_includes`: USE eager loading detected → Record => [:attachments], Attachment => [:project]
* After `mongoid_includes`: USE eager loading detected → Record => [:attachments], Attachment => [:project]

#### 2. Attempt to fix N+1 for Attachments
```rb
Bullet.profile do
  query = Record.where(project_id: '621ea9b069ca9c07aec7e36d')
  query.includes(:attachments).map do |r| 
    r.attachments.map do |a|
      a.project.id
    end
  end
end
```

* Before `mongoid_includes`: USE eager loading detected → Attachment => [:project]
* After `mongoid_includes`: USE eager loading detected → Record => [:attachments], Attachment => [:project] 😱 

#### 3. Attempt to fix N+1 for Attachments and Projects (nested includes)
```rb
Bullet.profile do
  query = Record.where(project_id: '621ea9b069ca9c07aec7e36d')
  query.includes(:attachments).includes(:project, from: :attachments).map do |r| 
    r.attachments.includes(:project).map do |a|
      a.project.id
    end
  end
end
```

* Before `mongoid_includes`: _Error: NameError: undefined local variable or method `_klass' for #<Mongoid::Criteria:0x00007fe2f6d787b0>_
* After `mongoid_includes`: USE eager loading detected → Record => [:attachments], Attachment => [:project] 😱😱

# Conclusion 💬

1. The `mongoid_includes` gem is not working even for the most basic `.includes`, as showing in **1.** and **2.** 🚨
2. It is also not working for nested includes, as shown in **3.** 🚨
3. The builtin `.includes` from mongoid is working for **1.** and **2.**, but after we add the `mongoid_inclues` gem to our Gemfile and install it, the builtin `.includes` method stops to work 😱 🚨

# Versions 📍

1. **Ruby**: ruby 2.6.8p205
2. **Rails**: Rails 6.0.5.1
4. **Mongoid**: 7.0.13
5. **Mongoid Includes**: 3.0.0

**Comment by ElMassimo** [comment]
This project includes [tests for Mongoid 7 to verify N+1 queries are not triggered](https://github.com/ElMassimo/mongoid_includes/blob/master/spec/mongoid/includes/simple_inclusions_spec.rb#L134-L138).

This sounds like an incompatibility with Bullet:

- https://github.com/ElMassimo/mongoid_includes/issues/4#issuecomment-223735985

It's understandable that Bullet does not support this gem, and I don't have plans to patch Bullet to add compatibility.

**Comment by ElMassimo** [comment]
As a sidenote, I found the 🚨 and 😱 to be distracting.

If something is broken, a maintainer would already understand how severe a bug is with a plain report.

**Comment by Victorcorcos** [comment]
Thank you for the very quick answer, @ElMassimo !

Looks like the Bullet gem does not detect the N+1 Query fixes from this gem.

Right on the spot!
