### ISSUE TITLE
Support for mongoid 8.0

### ISSUE THREAD

**Issue by danarnold** [ElMassimo/mongoid_includes#18]
Are there any plans to support mongoid 8.0?

**Comment by ElMassimo** [comment]
I'm no longer using MongoDB on a regular basis, but I just cut a new release that should allow you to install this library with Mongoid 8.

Let me know how it goes!

**Comment by danarnold** [comment]
Thanks for the quick reply and action. I'll be sure to reply with any updates.

**Comment by danarnold** [comment]
We've been using this code in production since Monday without any issues. Things seem to be working well. 👍

**Comment by 1st8** [comment]
I am seeing N+1 with Mongoid 8.1 (and a polymorphic belongs_to).

@danarnold Are you sure there are no hidden N+1 happening in you system?

Will report here when I know more.

**Comment by 1st8** [comment]
Figured out that it was a combination of inheritance on the class being queried and polymorphic belongs_to.

Querying on the base class with `BaseClass.includes(:something_polymorphic).where(_type: "MyExtendedClass")` fortunately works around the issue.

**Comment by danarnold** [comment]
@1st8 The failing test referenced in PR #21 is one relating to polymorphic belongs_to:

```
Mongoid::Includes::Criteria#includes multiple inclusions through polymorphic associations :with inclusions should not be overriden
```

So, it makes sense that this might be broken here as well, since the test was failing before any of my changes. I didn't test mongoid versions before 8 to see how far back this issue goes.

The app I work on that uses mongoid_includes doesn't have any of this type of association, so it isn't something that I would've noticed outside of the test failure, and when I reported that it was working in my 2022 comment, it was in the context of this same app.
