### ISSUE TITLE
Some compatibilities issues with bullet

### ISSUE THREAD

**Issue by aledalgrande** [ElMassimo/mongoid_includes#4]
The gem doesn't seem to work well with bullet, after declaring:
```
Trend.[...].includes(:page, :product_collection).includes(:products, from: :product_collection)
```
I get this from bullet:
```
N+1 Query detected
  Trend => [:page]
  Add to your finder: :includes => [:page]

N+1 Query detected
  Trend => [:product_collection]
  Add to your finder: :includes => [:product_collection]

N+1 Query detected
  ProductCollection => [:products]
  Add to your finder: :includes => [:products]
```

**Comment by ElMassimo** [comment]
Thanks for reporting this, I have never tried using bullet in combination with this gem. I'll dig into bullet to see what they are doing to detect [N+1 queries](http://maximomussini.com/posts/mongoid-n+1/), and see if there's a way to restore compatibility.

**Comment by ElMassimo** [comment]
By the way, which version of Mongoid are you using @aledalgrande?

**Comment by aledalgrande** [comment]
Currently using mongoid 5.1.3

**Comment by aledalgrande** [comment]
Hey, just wanted to report that, after discovering that Mongoid >= 5.1.0 supports nested includes natively, I tried it and Bullet still was crying wolf. But when I deactivated Bullet, I looked at the queries in the Rails log, and the n+1 was gone. I guess it is Bullet that has problems with Mongoid.

**Comment by ElMassimo** [comment]
@aledalgrande Does it? Wasn't available when I initially wrote the library, could you point out documentation or some examples of how to use nested includes?

**Comment by aledalgrande** [comment]
Well, the documentation sucks really bad since when the MongoDB team took it on, and their Changelog is not on Google, so I guess they like secrecy. Anyway, look at this: https://github.com/mongodb/mongoid/releases/tag/v5.1.0

One of the updates is **MONGOID-4173: Support nested eager loading**.

**Comment by ElMassimo** [comment]
Gotcha, it's a recent addition. Still like to be able to modify the eager load query arbitrarily, so I'll maintain support for this gem. Thanks!

**Comment by Victorcorcos** [comment]
Great debate guys, I was facing the same issue here.
