### ISSUE TITLE
Transfer mongoid_includes to github/mongoid? #49

### ISSUE THREAD

**Issue by Fudoshiki** [ElMassimo/mongoid_includes#8]
Hi, related https://github.com/simi/mongoid_paranoia/issues/49
@ElMassimo what do you thing?

**Comment by ElMassimo** [comment]
I think that would be nice, not sure if this gem is popular enough to add it to the org, though.

**Comment by dblock** [comment]
I think preserving these for posterity is better than not. Happy to take this gem. Transfer it to me and I'll move it into the mongoid org. Thanks!

**Comment by Fudoshiki** [comment]
@ElMassimo ping

**Comment by ElMassimo** [comment]
I'm using this gem in production, and I plan to actively maintain it in the foreseeable future.

What would be the advantage of transferring the repo to the organization?

In the event that I no longer intend to maintain it, I'll happily transfer it 😃

**Comment by dblock** [comment]
There're two clear advantages:

* Right now only @ElMassimo can add other maintainers, so the bus factor is 1, if anything happens there's no way anyone can recover admin access to this repo (Github doesn't support multiple project admins on non-org accounts).
* It helps the project to be more discoverable. 
 
We're not trying to achieve anything else, so really nothing changes other than the above.

**Comment by FunkyloverOne** [comment]
@ElMassimo come on, it's a great gem, it's a shame it still has no support for Mongoid 7 :)

**Comment by dblock** [comment]
> @ElMassimo come on, it's a great gem, it's a shame it still has no support for Mongoid 7 :)

@FunkyloverOne You should contribute a PR that adds it!

**Comment by FunkyloverOne** [comment]
@dblock hehe, maybe one day, when I will truly understand those internals of mongoid :D

**Comment by paul-mesnilgrente** [comment]
Is it going to be maintained again in the near future? I tried nested eager loading with mongoid but it still doesn't work apparently. I don't have time for supporting mongoid 7 unfortunately :/

**Comment by ElMassimo** [comment]
I will add support for Mongoid 7 once we upgrade Mongoid in the main project I'm using this library. No timeline on that yet. In the meantime, PRs are accepted.

**Comment by ElMassimo** [comment]
@paul-mesnilgrente Added support for Mongoid 7 in #15.
